### 1. A country, called Simpleland, has a language with a small vocabulary of just “the”, “on”, “and”, “go”, “round”, “bus”, and “wheels”. For a word count vector with indices ordered as the words appear above, what is the word count vector for a document that simply says “the wheels on the bus go round and round.”

### Please enter the vector of counts as follows: If the counts were ["the"=1, “on”=3, "and"=2, "go"=1, "round"=2, "bus"=1, "wheels"=1], enter 1321211.

In [1]:
text="the wheels on the bus go round and round"
print(set(text.split()))

set(['and', 'on', 'bus', 'round', 'go', 'the', 'wheels'])


In [18]:
2111211

2111211

### 2. In Simpleland, a reader is enjoying a document with a representation: [1 3 2 1 2 1 1]. Which of the following articles would you recommend to this reader next?

In [14]:
posibilities=[[7, 0, 2, 1, 0, 0, 1],[1, 7, 0, 0, 2, 0, 1],[1, 0, 0, 0, 7, 1, 2], [0, 2, 0, 0, 7, 1, 1]]
reader= [1 ,3 ,2 ,1 ,2 ,1 ,1]
import numpy as np

In [17]:
# similarity = cos(theta) = v1 * v2 / ||v1|| * ||v2||
# this is the cosine. the bigger cos(theta) the more parallel vectors (cos(0)=1 => parallalel and same direction)

for v in posibilities:
        v2=np.array(v)
        v1=np.array(reader)
        print(v2, np.dot(v1,v2)/(np.linalg.norm(v2)*np.linalg.norm(reader)))

(array([7, 0, 2, 1, 0, 0, 1]), 0.3825184261187248)
(array([1, 7, 0, 0, 2, 0, 1]), 0.7944613465542745)
(array([1, 0, 0, 0, 7, 1, 2]), 0.5296408977028497)
(array([0, 2, 0, 0, 7, 1, 1]), 0.6473388749701496)


### 3. A corpus in Simpleland has 99 articles. If you pick one article and perform 1-nearest neighbor search to find the closest article to this query article, how many times must you compute the similarity between two articles?

In [ ]:
98

### 5.Question 5 Which of the following statements are true? (Check all that apply):

### 6.Question 6 Which of the following pictures represents the best k-means solution? (Squares represent observations, plus signs are cluster centers, and colors indicate assignments of observations to cluster centers.)
